# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"setup_dirs": "00_core.ipynb",
         "find_next_script": "00_core.ipynb",
         "safe_rename": "00_core.ipynb",
         "ResourcePoolBase": "00_core.ipynb",
         "FixedWorkerPool": "00_core.ipynb",
         "ResourcePoolGPU": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastgpu.github.io/"

git_url = "https://github.com/fastai/fastgpu/tree/master/"

def custom_doc_links(name): return None